---
- name: Prepares testing environment. Step 1. Prep
  hosts: all
  become: true
  tasks:
    - name: checks python package
      raw: apt update && apt install -y python-all
      tags:
        - raw
        - step1

    - name: checks packages
      apt: name={{item}} state=present
      loop: "{{common_pkg_list}}"
      loop_control:
        label: "{{item}}"
      when:
        - common_pkg_list is defined
        - common_pkg_list
      tags:
        - pkg
        - step1

- name: Prepares testing environment. Step 2. Registry container
  hosts: reg
  become: true
  gather_facts: false
  tasks:
    - name: checks registry container
      docker_container:
        name: mynexus
        image: sonatype/nexus3
        ports: 
          - 8081:8081
          - "{{reg_port}}:{{reg_port}}"
        volumes: nexus:/nexus-data
        state: started
      tags:
        - reg
        - step2

    - name: sleeps for some time
      pause: seconds=120
      tags:
        - reg
        - step2

    - name: gets default password
      shell: cat /var/lib/docker/volumes/nexus/_data/admin.password
      register: reg_pass
      tags:
        - reg
        - step2

    - name: prints default password
      debug:
        msg: "registry default admin password: {{reg_pass.stdout}}"
      tags:
        - reg
        - step2

- name: Prepares testing environment. Step 3. Automation container
  hosts: aut
  become: true
  gather_facts: false
  tasks:
    - name: checks jenkins container
      docker_container:
        name: myjenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
          - 8080:8080
          - 50000:50000
        volumes: jenkins:/var/jenkins_home
        state: started
        restart_policy: on-failure
      tags:
        - aut
        - step3

    - name: sleeps for some time
      pause: seconds=120
      tags:
        - aut
        - step3

    - name: gets default password
      shell: cat /var/lib/docker/volumes/jenkins/_data/secrets/initialAdminPassword
      register: jenkins_pass
      tags:
        - aut
        - step3

    - name: prints default password
      debug:
        msg: "jenkins default admin pass: {{jenkins_pass.stdout}}"
      tags:
        - aut
        - step3
